FE

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -87,17 +87,13 @@ jobs:
     
     - name: Run ${{ matrix.app }} linter
       run: |
-          if [ "${{ matrix.app }}" = "backend" ]; then
-            if [ -d "${{ matrix.app }}" ]; then
-              cd ${{ matrix.app }}
-              npx eslint --config eslint.config.cjs **/*.cjs
-            else
-              echo "${{ matrix.app }} directory not found"
-              exit 1
-            fis
-          else
-            echo "Skipping linter for ${matrix.app}"
-          fi
+        if [ "${{ matrix.app }}" = "backend" ]; then
+          cd backend
+          npx eslint --config eslint.config.cjs **/*.cjs
+        else
+          echo "${{ matrix.app }} directory not found"
+          exit 1
+        fi
     
 
   deploy:
